name: Trigger Colab Notebook

on:
  schedule:
    - cron: "5 */12 * * *"
  workflow_dispatch:

jobs:
  run-colab:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install ChromeDriver
        run: |
          sudo apt-get install -y chromium-chromedriver

      - name: Install dependencies
        run: pip install selenium

      - name: Run controller.py with Xvfb (virtual display)
        run: |
          xvfb-run -a python controller.py

      - name: Upload Screenshot (before run)
        uses: actions/upload-artifact@v4
        with:
          name: colab-screenshot
          path: colab_screen.png

      - name: Upload Screenshot (after run)
        uses: actions/upload-artifact@v4
        with:
          name: colab-screenshot-after
          path: colab_screen_after.png

