name: Trigger Colab Notebook

on:
  schedule:
    - cron: "5 */12 * * *"   # every 12 hours + 5 min
  workflow_dispatch:

jobs:
  run-colab:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install selenium webdriver-manager

      - name: Run Colab Trigger
        run: python controller.py

      - name: Upload Screenshot (if any)
        uses: actions/upload-artifact@v3
        with:
          name: colab-screenshot
          path: colab_screen.png

